### ISSUE TITLE
Render Viewport Scale Unsupported

### ISSUE THREAD

**Issue by davidfoster** [keijiro/MiniEngineAO#3] opened 2017-08-09 12:01 UTC
Firstly: MiniEngineAO is awesome. Amazing quality considering how performantly it runs.

Changing [VRSettings.renderViewportScale](https://docs.unity3d.com/ScriptReference/VR.VRSettings-renderViewportScale.html), or specifically making it less than 1, causes MiniEngineAO to render to a smaller portion of the bottom left of the screen.

Here is a quick capture of what happens when adaptively scaling render viewport scale: https://youtu.be/9w9ViiswIRA

I suspect a shader will need `1 / VRSettings.renderViewportScale` passing in to scale all incoming UVs in the vertex program.

**Comment by keijiro** [comment] 2017-08-21 07:55
This is actually a bug in the Unity side.

https://issuetracker.unity3d.com/issues/vr-changing-renderviewportscale-results-in-reduction-of-viewing-space-for-the-right-eye-when-using-post-effects

The symptom described in the issue above is a bit different from what you told, but the root cause of the problem is the same.

I'm closing this issue. Please follow the issue tracker for further updates.

**Closed as completed by keijiro** 2017-08-21 07:55 UTC
Labels: bug
